export interface Post {
  slug: string;
  title: string;
  summary: string;
  body: string[]; // paragrafos; itens iniciados por "## " viram h2
}

export const posts: Post[] = [
  {
    slug: 'como-se-preparar-para-a-mudanca',
    title: 'Como se preparar para a mudança',
    summary: 'Um roteiro simples para organizar caixas, móveis e acessos antes do dia da mudança.',
    body: [
      'Uma mudança tranquila começa dias antes do caminhão chegar. Quanto mais organizado estiver o que vai ser transportado, mais rápido é o carregamento e menor o risco de esquecer algo.',
      '## Comece pelo que você não usa',
      'Separe o que vai doar, vender ou descartar antes de embalar. Levar menos coisas reduz o volume, facilita o transporte e deixa o novo endereço mais leve desde o primeiro dia.',
      '## Embale por cômodo',
      'Use caixas resistentes, identifique cada uma com o cômodo de destino e escreva na lateral, não só em cima, para ler mesmo quando estiverem empilhadas. Itens frágeis ficam em caixas menores, bem protegidos com papel ou cobertor.',
      '## Desmonte e proteja os móveis',
      'Guarde parafusos e peças pequenas em um saquinho preso ao próprio móvel. Cantos e superfícies delicadas merecem proteção com cobertores ou papelão.',
      '## Confirme os acessos nos dois endereços',
      'Veja se há elevador, escadas, ruas estreitas ou restrição de horário para caminhões no prédio ou condomínio. Avisar isso ao pedir orçamento evita surpresas no dia.',
      '## Faça um planejamento de datas',
      'Defina o dia da mudança com antecedência e organize a rotina nas semanas anteriores: comece pelos cômodos menos usados e deixe o essencial para o final. Cancele ou transfira serviços como internet, gás e água, e avise o condomínio sobre o horário do caminhão.',
      '## Reserve uma caixa de primeira necessidade',
      'Separe uma caixa ou mala com itens para a primeira noite: roupas, itens de higiene, carregadores, documentos e utensílios básicos. Assim você não precisa abrir várias caixas logo na chegada.',
    ],
  },
  {
    slug: 'o-que-informar-para-pedir-orcamento-de-frete',
    title: 'O que informar para pedir orçamento de frete',
    summary: 'Os dados que ajudam a receber um orçamento mais preciso pelo WhatsApp.',
    body: [
      'Um orçamento de frete depende de poucas informações, mas elas precisam estar claras. Reunir esses dados antes de chamar agiliza a resposta e evita idas e vindas.',
      '## O que carregar',
      'Descreva os itens: móveis, eletrodomésticos, caixas ou outro tipo de carga. Se puder, informe a quantidade aproximada, as medidas dos itens maiores e se algo é frágil ou pesado.',
      '## Origem e destino',
      'Informe bairro e cidade de retirada e de entrega. O trajeto é um dos principais fatores para definir o serviço.',
      '## Condições de acesso',
      'Diga se há escada, elevador, rua estreita ou horário restrito. Se houver necessidade de ajudantes para carregar, avise também.',
      '## Data e horário',
      'Combine o dia e o período em que o serviço é necessário. Para datas de grande procura, como finais de mês, pedir com antecedência ajuda.',
      '## Fotos ajudam',
      'Quando houver itens grandes ou de formato incomum, uma foto enviada pelo WhatsApp ajuda a entender o tamanho e a melhor forma de carregar. Também vale mandar uma foto da entrada do local, se o acesso for apertado.',
      '## Informe se o local tem restrições',
      'Prédios e condomínios podem ter horário para mudanças, regras para uso do elevador ou limite de altura para veículos. Avisar com antecedência permite combinar o serviço de forma que respeite essas regras e evite atrasos.',
      '## Tenha um contato no local',
      'Deixe o telefone de quem estará na retirada e na entrega. Isso facilita ajustes de última hora, como mudança de horário ou dificuldade para encontrar o endereço.',
    ],
  },
  {
    slug: 'checklist-para-o-dia-da-mudanca',
    title: 'Checklist para o dia da mudança',
    summary: 'O que conferir na manhã da mudança para o carregamento correr bem.',
    body: [
      'No dia da mudança, o objetivo é que tudo esteja pronto quando a equipe chegar. Um checklist curto ajuda a não deixar nada para a última hora.',
      '## Antes de o caminhão chegar',
      'Confira se os móveis estão desmontados e as caixas fechadas e identificadas. Deixe corredores e a entrada livres para circular com volumes grandes.',
      '## Documentos e itens de valor',
      'Documentos, joias, dinheiro e eletrônicos pequenos devem ir com você, e não no caminhão.',
      '## Durante o carregamento',
      'Acompanhe a retirada, indique o que é frágil e confirme o que vai em cada viagem. Fotografar o estado dos móveis antes ajuda a conversar com clareza depois.',
      '## Ao chegar ao destino',
      'Indique em qual cômodo cada caixa deve ficar. Antes de liberar a equipe, confira se tudo chegou e se o local de origem ficou vazio.',
      '## Cuide dos itens que dão trabalho',
      'Esvazie e desligue a geladeira com antecedência para que ela esteja seca no transporte. Fogões, máquinas de lavar e outros aparelhos devem ter mangueiras e fios recolhidos e presos.',
      '## Combine as regras do condomínio',
      'Confirme com a portaria o horário e o local de estacionamento do caminhão, e se é preciso reservar o elevador de serviço. Deixar isso resolvido evita filas e atrasos no carregamento.',
      '## Tenha água e um pouco de tempo',
      'Mudanças costumam levar mais tempo do que o planejado. Deixe água disponível, reserve a manhã ou a tarde inteira para o serviço e evite compromissos marcados logo em seguida.',
    ],
  },
  {
    slug: 'descarte-correto-de-entulho-de-obra',
    title: 'Descarte correto de entulho de obra',
    summary: 'Por que separar e retirar o entulho corretamente e o que ter em mente ao contratar.',
    body: [
      'Reformas e pequenas obras geram entulho: restos de alvenaria, cerâmica, madeira e embalagens. Esse material não deve ser deixado na calçada nem misturado ao lixo comum.',
      '## Separe antes de retirar',
      'Separar entulho mineral, madeira, metais e recicláveis facilita o transporte e permite que cada material siga para o destino adequado.',
      '## Acondicione com segurança',
      'Use sacos resistentes ou recipientes apropriados para evitar que o material se espalhe e atrapalhe vizinhos e a circulação.',
      '## Informe o tipo e a quantidade',
      'Ao pedir o serviço, descreva o tipo de material e o volume aproximado, além das condições de acesso ao local de retirada.',
      '## Confirme o destino',
      'Pergunte para onde o material será levado. Descartar em local regular faz parte de uma obra responsável.',
      '## Evite misturar materiais perigosos',
      'Tintas, solventes, lâmpadas e materiais que contenham amianto exigem atenção própria e não devem ir junto com o entulho comum. Se houver algo assim na obra, avise antes de pedir o serviço.',
      '## Programe a retirada junto com a obra',
      'Entulho acumulado ocupa espaço e atrapalha o trabalho. Combine retiradas em etapas, de acordo com o andamento da reforma, em vez de deixar tudo para o final.',
      '## Verifique o acesso ao local',
      'Informe se há escadas, portão estreito ou rua com limite de circulação para caminhões, pois isso influencia a forma de carregar e o tempo do serviço.',
    ],
  },
  {
    slug: 'frete-avulso-ou-mudanca-completa',
    title: 'Frete avulso ou mudança completa: como escolher',
    summary: 'Entenda as diferenças entre transportar poucos itens e mudar uma casa inteira.',
    body: [
      'Nem todo transporte é uma mudança completa. Escolher o serviço certo evita pagar por mais do que precisa ou contratar menos do que o necessário.',
      '## Quando o frete avulso resolve',
      'Para transportar poucos itens, como um sofá, uma geladeira ou algumas caixas, o frete avulso costuma atender. É indicado para compras, doações e pequenos deslocamentos.',
      '## Quando pensar em mudança completa',
      'Se você vai levar a casa inteira ou o escritório, com muitos móveis e caixas, a mudança envolve planejamento, mais volume e pode exigir ajudantes e mais de uma viagem.',
      '## Na dúvida, descreva o que vai levar',
      'Explique ao pedir orçamento o que precisa transportar. Com essa descrição, fica mais fácil indicar a melhor opção para o seu caso.',
      '## Considere o acesso e a distância',
      'Escadas, falta de elevador e ruas estreitas pesam tanto em um frete pequeno quanto em uma mudança grande. Descreva esses pontos no pedido para receber uma indicação mais adequada.',
      '## Pense no tempo disponível',
      'Um frete avulso costuma ser rápido, enquanto uma mudança completa pode ocupar o dia inteiro. Se você tem pouco tempo, planeje a embalagem e a desmontagem dos móveis com antecedência.',
      '## Dá para combinar os dois',
      'Alguns casos ficam no meio do caminho, como levar apenas os móveis grandes e transportar o resto por conta própria. Converse sobre a sua situação pelo WhatsApp e veja a melhor combinação.',
    ],
  },
  {
    slug: 'dicas-para-entregas-comerciais',
    title: 'Dicas para organizar entregas comerciais',
    summary: 'Como lojas e pequenos negócios podem organizar entregas com mais regularidade.',
    body: [
      'Quem tem loja, escritório ou pequeno negócio lida com entregas o tempo todo. Um pouco de organização torna esse processo mais previsível.',
      '## Padronize as embalagens',
      'Embalagens padronizadas e bem fechadas protegem o produto e facilitam o carregamento e a conferência.',
      '## Reúna os dados da entrega',
      'Mantenha endereço completo, telefone de contato e horário preferencial de cada destinatário. Informações claras evitam tentativas frustradas.',
      '## Agrupe entregas por região',
      'Entregas na mesma região podem ser planejadas juntas. Ao pedir orçamento, informe os bairros e a frequência das entregas.',
      '## Combine o formato de atendimento',
      'Se a necessidade é recorrente, converse pelo WhatsApp sobre dias e horários para encontrar um formato que funcione para o seu negócio.',
      '## Defina janelas de horário',
      'Quando possível, combine períodos de entrega com os clientes, como manhã ou tarde. Janelas claras reduzem a chance de ninguém estar no local para receber.',
      '## Confira os itens antes de sair',
      'Fazer a conferência na saída, com uma lista simples, evita divergências no destino e facilita resolver qualquer problema depois.',
      '## Avise o cliente sobre a entrega',
      'Uma mensagem avisando que o pedido está a caminho ajuda o destinatário a se preparar e melhora a experiência de quem compra do seu negócio.',
    ],
  },
];
